version: '3.8'
name: nutritionist-assistant-project
services:
  nutritionist-assistant-service:
    image: glungov/nutritionist-assistant:1.0.0
    container_name: nutritionist-assistant-container
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    # Mantém o terminal interativo aberto para o seu app CLI funcionar
    stdin_open: true
    tty: true

    # Mapeia a pasta atual para dentro do container (para ler/salvar os arquivos)
    volumes:
      - .:/workspace
    working_dir: /workspace
