version: '3.8'
name: nutritionist-assistant-project
services:
  nutritionist-assistant-service:
    image: glungov/nutritionist-assistant:1.0.0
    container_name: nutritionist-assistant-container
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    # Keeps interactive terminal open to CLI works
    stdin_open: true
    tty: true

    # Maps the current directory into the container
    volumes:
      - .:/workspace
    working_dir: /workspace
