package com.app.service;

import java.io.*;
import java.util.Map;

import org.apache.poi.xwpf.usermodel.*;
import fr.opensagres.poi.xwpf.converter.pdf.PdfConverter;
import fr.opensagres.poi.xwpf.converter.pdf.PdfOptions;

public class DocumentService {


    /**
     * Loads word model, replaces the tags bese on XML map generated and export final result directly to PDF format.
     *
     * @param docxPath path to word model file
     * @param pdfOutputPath final path where PDF will be saved
     * @param placeholderMap Map<K,V> generated by XmlService
     * @throws Exception in case reading, writing or substitution failure
     */

    public void generatedPdfFromDocx(String docxPath, String pdfOutputPath, Map<String, String> placeholderMap) throws Exception {
        File docxFile = new File(docxPath);

        if (!docxFile.exists()) {
            throw new FileNotFoundException("The specified XML could not be found in" + docxPath);
        }

        // Opens Word in memory using Apache POI
        try (
        InputStream docxStream = new FileInputStream(docxFile);
        XWPFDocument document = new XWPFDocument(docxStream)) {

            // Replaces tags inside common text paragraphs
            for (XWPFParagraph paragraph : document.getParagraphs()) {
                replaceTagsInParagraph(paragraph, placeholderMap);
            }

            // Replaces tags hidden inside tables
            for (XWPFTable table : document.getTables()) {
                for (XWPFTableRow row : table.getRows()) {
                    for (XWPFTableCell cell : row.getTableCells()) {
                        for (XWPFParagraph paragraph : cell.getParagraphs()) {
                            replaceTagsInParagraph(paragraph, placeholderMap);
                        }
                    }
                }
            }

            // Converts modified document in memory to PDF
            File pdfFile = new File(pdfOutputPath);
            try (OutputStream pdfStream = new FileOutputStream(pdfFile)) {
                PdfOptions options = PdfOptions.create();
                PdfConverter.getInstance().convert(document, pdfStream, options);
            }
        }
    }

    /**
     * Replaces tags in a specific paragraph
     */

    private void replaceTagsInParagraph(XWPFParagraph paragraph, Map<String, String> placeholderMap) {
        String paragraphText = paragraph.getText();

        // Validates in paragraph contains any key from map
        for (Map.Entry<String, String> entry : placeholderMap.entrySet()) {
            if (paragraphText.contains(entry.getKey())) {

                // Remove old text stylized text blocks (runs) from Apache POI to avoid duplicity
                int runSize = paragraph.getRuns().size();
                for (int i = runSize -1; i>= 0; i--) {
                    paragraph.removeRun(i);
                }

                // Replaces tag by the real value from XML
                paragraphText = paragraphText.replace(entry.getKey(), entry.getValue());

                // Creates new text block on paragraph with updated data
                XWPFRun newRun = paragraph.createRun();
                newRun.setText(paragraphText);
            }
        }
    }
}
